name: Publish Docker image
on:
  push:
    branches:
      - 'main'
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to Google Cloud Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          # TODO: this could be the branch or the tag if release...
          tags: |
            ghcr.io/n3wscott/learning-nc-server:latest
            gcr.io/${{ secrets.GCR_PROJECT }}/learning-nc-server:latest
      - name: Image digest
        run: echo Build and Published ${{ steps.docker_build.outputs.digest }}
